// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

library;

import 'package:amplify_analytics_pinpoint/amplify_analytics_pinpoint.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter_test/flutter_test.dart';

/// Presence of this file opts the example into the `dart2wasm` E2E leg
/// (`run-wasm: true`) generated by `aft`. It also smoke-tests that the plugin
/// and event types work.
void main() {
  // `AmplifyAnalyticsPinpoint()` wires up the Flutter widget life cycle, which
  // needs an initialized binding.
  TestWidgetsFlutterBinding.ensureInitialized();

  group('WASM smoke test', () {
    test('plugin is constructable', () {
      expect(AmplifyAnalyticsPinpoint(), isA<AmplifyAnalyticsPinpoint>());
    });

    test('AnalyticsEvent builds with typed properties', () {
      final event = AnalyticsEvent('smoke')
        ..customProperties.addIntProperty('intKey', 10)
        ..customProperties.addDoubleProperty('doubleKey', 10.1);
      expect(event.name, 'smoke');
      // `metrics` coerces int properties to double; exercises that path.
      expect(event.customProperties.metrics['intKey'], 10.0);
    });
  });
}
