//
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, PermissionStatus) {
  PermissionStatusShouldRequest = 0,
  PermissionStatusShouldExplainThenRequest = 1,
  PermissionStatusGranted = 2,
  PermissionStatusDenied = 3,
};

/// Wrapper for PermissionStatus to allow for nullability.
@interface PermissionStatusBox : NSObject
@property(nonatomic, assign) PermissionStatus value;
- (instancetype)initWithValue:(PermissionStatus)value;
@end

@class PermissionsOptions;
@class GetPermissionStatusResult;

@interface PermissionsOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAlert:(BOOL )alert
    sound:(BOOL )sound
    badge:(BOOL )badge;
@property(nonatomic, assign) BOOL  alert;
@property(nonatomic, assign) BOOL  sound;
@property(nonatomic, assign) BOOL  badge;
@end

@interface GetPermissionStatusResult : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithStatus:(PermissionStatus)status;
@property(nonatomic, assign) PermissionStatus status;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetPushNotificationsNativePluginCodec(void);

@interface PushNotificationsFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)onNotificationReceivedInBackgroundWithPayload:(NSDictionary<id, id> *)withPayload completion:(void (^)(FlutterError *_Nullable))completion;
- (void)nullifyLaunchNotificationWithCompletion:(void (^)(FlutterError *_Nullable))completion;
@end


@protocol PushNotificationsHostApi
- (void)requestInitialTokenWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)getPermissionStatusWithCompletion:(void (^)(GetPermissionStatusResult *_Nullable, FlutterError *_Nullable))completion;
- (void)requestPermissionsWithPermissionOptions:(PermissionsOptions *)withPermissionOptions completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (nullable NSDictionary<id, id> *)getLaunchNotificationWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getBadgeCountWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setBadgeCountWithBadgeCount:(NSInteger)withBadgeCount error:(FlutterError *_Nullable *_Nonnull)error;
- (void)registerCallbackFunctionCallbackHandle:(NSInteger)callbackHandle error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpPushNotificationsHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PushNotificationsHostApi> *_Nullable api);

extern void SetUpPushNotificationsHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PushNotificationsHostApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
