// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

library;

import 'package:amplify_db_common/amplify_db_common.dart';
import 'package:drift/backends.dart';
import 'package:flutter_test/flutter_test.dart';

/// Presence of this file opts the example into the `dart2wasm` E2E leg
/// (`run-wasm: true`) generated by `aft`, so the drift round-trip in
/// `integration_test/main_test.dart` runs against a real `sqlite3.wasm` under
/// dart2wasm as well as dart2js. It also smoke-tests that `connect` compiles
/// and builds a lazy executor on web.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('WASM smoke test', () {
    test('connect returns a lazy QueryExecutor', () {
      expect(connect(name: 'SmokeDatabase'), isA<QueryExecutor>());
    });
  });
}
