// dart format width=80
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// WorkerBeeGenerator
// **************************************************************************

// Generated by worker_bee_builder.

export 'secure_storage_worker.worker.vm.dart'
    if (dart.library.js_interop) 'secure_storage_worker.worker.js.dart';
