// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'amplify_core_test.dart' as amplify_core_test;

void main() {
  amplify_core_test.main();
}
