// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

library;

import 'dart:convert';

import 'package:amplify_core/amplify_core.dart';
import 'package:amplify_storage_s3/amplify_storage_s3.dart';
import 'package:flutter_test/flutter_test.dart';

/// Presence of this file opts the example into the `dart2wasm` E2E leg
/// (`run-wasm: true`) generated by `aft`. It also smoke-tests that the plugin
/// and model types work.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('WASM smoke test', () {
    test('plugin is constructable', () {
      expect(AmplifyStorageS3(), isA<AmplifyStorageS3>());
    });

    test('StoragePath builds', () {
      final path = StoragePath.fromString('public/a.txt');
      expect(path, isA<StoragePath>());
    });

    // A JSON `size` decodes to double under wasm, int under dart2js. Guards
    // the `.toInt()` coercion in S3Item.fromJson.
    test('S3Item decodes numeric size', () {
      const raw = '{"path":"public/a.txt","size":300000}';
      final item = S3Item.fromJson(jsonDecode(raw) as Map<String, Object?>);
      expect(item.size, 300000);
    });
  });
}
