// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';

part 'firehose_record_database.g.dart';

/// Table definition for Firehose records.
///
/// Note: Unlike Kinesis Data Streams, Firehose does not use partition keys.
class FirehoseRecords extends Table {
  /// Auto-incrementing primary key.
  IntColumn get id => integer().autoIncrement()();

  /// The delivery stream name.
  TextColumn get streamName => text()();

  /// The data blob.
  BlobColumn get data => blob()();

  /// Size of the data in bytes (for efficient batch size calculations).
  IntColumn get dataSize => integer()();

  /// Number of times this record has been retried.
  IntColumn get retryCount => integer().withDefault(const Constant(0))();

  /// Timestamp when the record was created (milliseconds since epoch).
  IntColumn get createdAt => integer()();
}

/// Database for storing Firehose records locally.
@DriftDatabase(tables: [FirehoseRecords])
class FirehoseRecordDatabase extends _$FirehoseRecordDatabase {
  /// Creates a database at the specified path.
  FirehoseRecordDatabase(String path)
      : super(
          LazyDatabase(() async {
            final file = File('$path/firehose_records.db');
            return NativeDatabase.createInBackground(file);
          }),
        );

  /// Creates an in-memory database for testing.
  FirehoseRecordDatabase.forTesting()
      : super(NativeDatabase.memory());

  @override
  int get schemaVersion => 1;
}

/// Type alias for a stored record from the database.
/// The [FirehoseRecord] class is generated by Drift from the [FirehoseRecords] table.
typedef StoredRecord = FirehoseRecord;
