var authErrorTypes = [
  "AMPLIFY_CONFIRM_SIGNIN_FAILED",
  "AMPLIFY_CONFIRM_SIGNUP_FAILED",
  "AMPLIFY_SIGNIN_FAILED",
  "AMPLIFY_SIGNOUT_FAILED",
  "AMPLIFY_SIGNUP_FAILED",
  "AMPLIFY_REQUEST_MALFORMED",
  "ERROR_CASTING_INPUT_IN_PLATFORM_CODE",
  "PLATFORM_EXCEPTIONS"
];
