// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

library;

import 'package:amplify_firehose/amplify_firehose.dart';
import 'package:flutter_test/flutter_test.dart';

/// Presence of this file opts the example into the `dart2wasm` E2E leg
/// (`run-wasm: true`) generated by `aft`. It also smoke-tests that the
/// public types build.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('WASM smoke test', () {
    test('options build', () {
      const options = AmplifyFirehoseClientOptions(
        flushStrategy: FlushInterval(interval: Duration(seconds: 10)),
      );
      expect(options.flushStrategy, isA<FlushInterval>());
    });
  });
}
