// Generated by worker_bee_builder.

import 'package:aws_common/aws_common.dart';
import 'package:worker_bee_example/workers/echo_worker.dart';

/// The JS implementation of [EchoWorker].
class EchoWorkerImpl extends EchoWorker {
  @override
  String get name => 'EchoWorker';

  @override
  List<String> get fallbackUrls {
    // When running in a test, we need to find the `packages` directory which
    // is symlinked in the root `test/` directory.
    final baseUri = Uri.base;
    final basePath = baseUri.pathSegments
        .takeWhile((segment) => segment != 'test')
        .map(Uri.encodeComponent)
        .join('/');
    const relativePaths = zDebugMode
        ? [
            'packages/worker_bee_example/workers.js',
            'packages/worker_bee_example/workers.debug.dart.js',
          ]
        : [
            'packages/worker_bee_example/workers.min.js',
            'packages/worker_bee_example/workers.release.dart.js',
          ];
    return [
      for (final relativePath in relativePaths) ...[
        relativePath,
        Uri(
          scheme: baseUri.scheme,
          host: baseUri.host,
          port: baseUri.port,
          path: '$basePath/test/$relativePath',
        ).toString(),
      ],
    ];
  }
}
