// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format width=80

// **************************************************************************
// WorkerBeeGenerator
// **************************************************************************

// Generated by worker_bee_builder.

export 'srp_init_worker.worker.vm.dart'
    if (dart.library.js_interop) 'srp_init_worker.worker.js.dart';
