import Foundation
enum FlutterAuthErrorMessage: String {
    case CASTING = "ERROR_CASTING_INPUT_IN_PLATFORM_CODE"
    case CONFIRM_SIGNIN = "AMPLIFY_CONFIRM_SIGNIN_FAILED"
    case CONFIRM_SIGNUP = "AMPLIFY_CONFIRM_SIGNUP FAILED"
    case ERROR_SENDING = "AMPLIFY_REQUEST_FAILED_TO_SEND"
    case INVALID_STATE = "AMPLIFY_INVALID_STATE"
    case MALFORMED = "AMPLIFY_SIGNUP_REQUEST_MALFORMED"
    case SIGNIN = "AMPLIFY_SIGNIN_FAILED"
    case SIGNOUT = "AMPLIFY_SIGNOUT_FAILED"
    case SIGNUP = "AMPLIFY_SIGNUP_FAILED"
}
