// Generated by worker_bee_builder.

import 'package:aws_common/aws_common.dart';
import 'package:e2e/e2e_worker.dart';

/// The JS implementation of [E2EWorker].
class E2EWorkerImpl extends E2EWorker {
  @override
  String get name => 'E2EWorker';
  @override
  List<String> get fallbackUrls => zDebugMode
      ? const ['packages/e2e/workers.debug.dart.js']
      : const ['packages/e2e/workers.release.dart.js'];
}
