include: package:amplify_lints/app.yaml

analyzer:
  exclude:
    - lib/models/*
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    avoid_print: false
