// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _5: Date.now,
      _7: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _9: () => new Error().stack,
      _13: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _14: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _15: () => new WeakMap(),
      _16: (map, o) => map.get(o),
      _17: (map, o, v) => map.set(o, v),
      _18: (exn) => exn.toString(),
      _19: (exn) => exn.stack,
      _20: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _33: s => JSON.stringify(s),
      _34: s => printToConsole(s),
      _35: (o, p, r) => o.replaceAll(p, () => r),
      _36: (o, p, r) => o.replace(p, () => r),
      _37: Function.prototype.call.bind(String.prototype.toLowerCase),
      _38: s => s.toUpperCase(),
      _39: s => s.trim(),
      _42: (string, times) => string.repeat(times),
      _43: Function.prototype.call.bind(String.prototype.indexOf),
      _44: (s, p, i) => s.lastIndexOf(p, i),
      _45: (string, token) => string.split(token),
      _46: Object.is,
      _49: (o, t) => typeof o === t,
      _51: o => Object.keys(o),
      _53: (o,s,v) => o[s] = v,
      _82: x0 => new Array(x0),
      _84: x0 => x0.length,
      _86: (x0,x1) => x0[x1],
      _87: (x0,x1,x2) => { x0[x1] = x2 },
      _91: (x0,x1,x2) => new DataView(x0,x1,x2),
      _93: x0 => new Int8Array(x0),
      _94: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _95: x0 => new Uint8Array(x0),
      _97: x0 => new Uint8ClampedArray(x0),
      _99: x0 => new Int16Array(x0),
      _101: x0 => new Uint16Array(x0),
      _103: x0 => new Int32Array(x0),
      _105: x0 => new Uint32Array(x0),
      _107: x0 => new Float32Array(x0),
      _109: x0 => new Float64Array(x0),
      _133: () => Symbol("jsBoxedDartObjectProperty"),
      _134: x0 => x0.random(),
      _137: () => globalThis.Math,
      _150: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _152: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _154: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _155: () => Date.now(),
      _156: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _157: (x0,x1) => x0.exec(x1),
      _158: (x0,x1) => x0.test(x1),
      _159: x0 => x0.pop(),
      _161: o => o === undefined,
      _163: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _165: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _166: o => o instanceof RegExp,
      _167: (l, r) => l === r,
      _168: o => o,
      _169: o => o,
      _170: o => o,
      _171: b => !!b,
      _172: o => o.length,
      _174: (o, i) => o[i],
      _175: f => f.dartFunction,
      _176: () => ({}),
      _177: () => [],
      _181: (o, p) => p in o,
      _182: (o, p) => o[p],
      _183: (o, p, v) => o[p] = v,
      _184: (o, m, a) => o[m].apply(o, a),
      _186: o => String(o),
      _187: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _188: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._188(f,arguments.length,x0) }),
      _189: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._189(f,arguments.length,x0,x1) }),
      _190: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _191: o => [o],
      _192: (o0, o1) => [o0, o1],
      _193: (o0, o1, o2) => [o0, o1, o2],
      _194: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _195: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _199: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _205: x0 => new ArrayBuffer(x0),
      _208: x0 => x0.index,
      _209: x0 => x0.groups,
      _210: x0 => x0.flags,
      _211: x0 => x0.multiline,
      _212: x0 => x0.ignoreCase,
      _213: x0 => x0.unicode,
      _214: x0 => x0.dotAll,
      _215: (x0,x1) => { x0.lastIndex = x1 },
      _217: (o, p) => o[p],
      _254: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._254(f,arguments.length,x0) }),
      _255: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _264: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._264(f,arguments.length,x0) }),
      _265: (x0,x1,x2) => x0.postMessage(x1,x2),
      _266: (x0,x1) => x0.postMessage(x1),
      _267: x0 => x0.close(),
      _268: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _269: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._269(f,arguments.length,x0) }),
      _300: () => globalThis.self,
      _302: o => o instanceof Array,
      _303: (a, i) => a.push(i),
      _310: (a, s, e) => a.slice(s, e),
      _313: a => a.length,
      _315: (a, i) => a[i],
      _319: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _321: o => o instanceof Uint8Array,
      _322: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _323: o => o instanceof Int8Array,
      _324: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _325: o => o instanceof Uint8ClampedArray,
      _326: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _327: o => o instanceof Uint16Array,
      _328: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _329: o => o instanceof Int16Array,
      _330: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _331: o => o instanceof Uint32Array,
      _332: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _333: o => o instanceof Int32Array,
      _334: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _337: o => o instanceof Float32Array,
      _338: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _339: o => o instanceof Float64Array,
      _340: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _341: (t, s) => t.set(s),
      _343: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _345: o => o.buffer,
      _346: o => o.byteOffset,
      _347: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _348: (b, o) => new DataView(b, o),
      _349: (b, o, l) => new DataView(b, o, l),
      _350: Function.prototype.call.bind(DataView.prototype.getUint8),
      _351: Function.prototype.call.bind(DataView.prototype.setUint8),
      _352: Function.prototype.call.bind(DataView.prototype.getInt8),
      _353: Function.prototype.call.bind(DataView.prototype.setInt8),
      _354: Function.prototype.call.bind(DataView.prototype.getUint16),
      _355: Function.prototype.call.bind(DataView.prototype.setUint16),
      _356: Function.prototype.call.bind(DataView.prototype.getInt16),
      _357: Function.prototype.call.bind(DataView.prototype.setInt16),
      _358: Function.prototype.call.bind(DataView.prototype.getUint32),
      _359: Function.prototype.call.bind(DataView.prototype.setUint32),
      _360: Function.prototype.call.bind(DataView.prototype.getInt32),
      _361: Function.prototype.call.bind(DataView.prototype.setInt32),
      _366: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _367: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _368: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _369: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _370: Function.prototype.call.bind(Number.prototype.toString),
      _371: Function.prototype.call.bind(BigInt.prototype.toString),
      _372: Function.prototype.call.bind(Number.prototype.toString),
      _2723: x0 => x0.data,
      _2727: x0 => x0.ports,
      _2757: (x0,x1) => { x0.onmessage = x1 },

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
