// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

library;

import 'package:amplify_api/amplify_api.dart';
import 'package:flutter_test/flutter_test.dart';

/// Presence of this file opts the example into the `dart2wasm` E2E leg
/// (`run-wasm: true`) generated by `aft`. It also smoke-tests that the plugin
/// and request types work.
void main() {
  // `AmplifyAPI()` wires up the Flutter widget life cycle, which needs an
  // initialized binding.
  TestWidgetsFlutterBinding.ensureInitialized();

  group('WASM smoke test', () {
    test('plugin is constructable', () {
      expect(AmplifyAPI(), isA<AmplifyAPI>());
    });

    test('GraphQLRequest builds', () {
      final request = GraphQLRequest<String>(document: 'query { __typename }');
      expect(request.document, 'query { __typename }');
      expect(request.id, isNotEmpty);
    });
  });
}
