enum CognitoSignUpException {
  INVALID_PARAMETER,
  USERNAME_EXISTS,
  CODE_DELIVERY_FAILURE,
  INTERNAL_ERROR,
  INVALID_LAMBDA_RESPONSE,
  INVALID_PASSWORD,
  NOT_AUTHORIZED,
  RESOURCE_NOT_FOUND,
  TOO_MANY_REQUESTS,
  TOO_MANY_FAILED_REQUESTS,
  UNEXPECTED_LAMBDA,
  USER_LAMBDA_VALIDATION,
  VALIDATION,
  UNKNOWN
}
