name: amplify_firehose
description: A Flutter implementation for streaming data to Amazon Data Firehose with offline support.
version: 2.11.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/main/packages/kinesis/amplify_firehose
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

topics:
  - aws
  - firehose
  - streaming
  - analytics
  - aws-amplify

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

platforms:
  ios:
  android:
  macos:
  windows:
  linux:
  web:

dependencies:
  amplify_firehose_dart: ">=0.1.0 <0.2.0"
  amplify_foundation_dart: ">=2.11.0 <2.12.0"
  flutter:
    sdk: flutter
  path_provider: ^2.1.0

dev_dependencies:
  amplify_lints: ">=3.1.4 <3.2.0"
  flutter_test:
    sdk: flutter
