include: package:amplify_lints/library.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    implementation_imports: error    


linter:
  rules:
    public_member_api_docs: false
