include: package:amplify_lints/app.yaml

analyzer:
  errors:
    avoid_print: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
