name: amplify_push_example
description: Example app for the amplify_push package.
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.1"

dependencies:
  amplify_push:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
