name: E2E (Linux)
on:
  workflow_call:
    inputs:
      working-directory:
        description: The working directory relative to the repo root
        required: true
        type: string
      package-name:
        description: The name of the package being tested
        required: true
        type: string
      needs-aws-config:
        description: Whether the E2E workflow needs configuration pulled from AWS
        required: true
        type: boolean

jobs:
  e2e-test-linux:
    runs-on: ubuntu-latest
    strategy:
      # Allows other matrix items to run if one fails
      fail-fast: false
      matrix:
        channel:
          - beta
          - stable
        # Skips e2e tests against beta on PRs
        exclude:
          - channel: ${{ (github.event_name == 'pull_request' && 'beta') || 'NONE' }}

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
          submodules: true

      - name: Dummy
        run: true
