name: Generate Workflows
on:
  push:
    branches:
      - main
      - stable
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00

jobs:
  test:
    name: Generate Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          submodules: true

      - name: Setup Dart
        uses: dart-lang/setup-dart@43c102f4dc9b9829c862401f0b64c7c9184eab4e # main
        with:
          sdk: stable

      - name: Setup aft
        shell: bash # Run in bash regardless of platform
        run: dart pub global activate -spath packages/aft

      - name: Generate Workflows
        run: aft generate workflows --set-exit-if-changed
