name: Generate Workflows
on:
  push:
    branches:
      - main
      - stable
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00

jobs:
  test:
    name: Generate Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          submodules: true

      - name: Setup Dart
        uses: dart-lang/setup-dart@03a180dbe1de8ea7fb700663cbb7d24ca4bbe82c # main
        with:
          sdk: stable

      - name: Setup aft
        shell: bash # Run in bash regardless of platform
        run: dart pub global activate -spath packages/aft

      - name: Generate Workflows
        run: aft generate workflows --set-exit-if-changed
