name: Kinesis E2E Tests
on:
  push:
    branches:
      - main
      - stable
    paths:
      - "packages/kinesis/**"
      - ".github/workflows/kinesis_e2e.yaml"
  pull_request:
    paths:
      - "packages/kinesis/**"
      - ".github/workflows/kinesis_e2e.yaml"
  workflow_dispatch:

defaults:
  run:
    shell: bash

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kinesis-data-streams-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
          submodules: true

      - name: Setup Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # 2.21.0
        with:
          cache: true
          channel: stable

      - name: Setup Dart
        uses: dart-lang/setup-dart@03a180dbe1de8ea7fb700663cbb7d24ca4bbe82c # main
        with:
          sdk: stable

      - name: Install native sqlite3
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Setup aft
        run: dart pub global activate -spath packages/aft

      - name: Bootstrap
        id: bootstrap
        timeout-minutes: 20
        run: aft bootstrap --fail-fast --include=aws_kinesis_datastreams --verbose

      - name: Fetch Amplify backend configurations
        uses: ./.github/composite_actions/fetch_backends
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          scope: aws_kinesis_datastreams
          secret-identifier: ${{ secrets.AWS_SECRET_IDENTIFIER }}

      - name: Run E2E tests
        working-directory: packages/kinesis/aws_kinesis_datastreams
        run: dart test test/e2e/ --tags=e2e

      - name: Log success/failure
        if: always()
        uses: ./.github/composite_actions/log_cw_metric_wrapper
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

          job-status: ${{ job.status }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          test-type: e2e
          working-directory: packages/kinesis/aws_kinesis_datastreams

          framework: dart
          flutter-dart-channel: stable
          dart-compiler: vm

  firehose-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
          submodules: true

      - name: Setup Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # 2.21.0
        with:
          cache: true
          channel: stable

      - name: Setup Dart
        uses: dart-lang/setup-dart@03a180dbe1de8ea7fb700663cbb7d24ca4bbe82c # main
        with:
          sdk: stable

      - name: Install native sqlite3
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Setup aft
        run: dart pub global activate -spath packages/aft

      - name: Bootstrap
        id: bootstrap
        timeout-minutes: 20
        run: aft bootstrap --fail-fast --include=aws_amazon_firehose --verbose

      - name: Fetch Amplify backend configurations
        uses: ./.github/composite_actions/fetch_backends
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          scope: aws_amazon_firehose
          secret-identifier: ${{ secrets.AWS_SECRET_IDENTIFIER }}

      - name: Run E2E tests
        working-directory: packages/kinesis/aws_amazon_firehose
        run: dart test test/e2e/ --tags=e2e

      - name: Log success/failure
        if: always()
        uses: ./.github/composite_actions/log_cw_metric_wrapper
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

          job-status: ${{ job.status }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          test-type: e2e
          working-directory: packages/kinesis/aws_amazon_firehose

          framework: dart
          flutter-dart-channel: stable
          dart-compiler: vm
