name: Kinesis E2E Tests
on:
  push:
    branches:
      - main
      - stable
    paths:
      - "packages/kinesis/**"
      - ".github/workflows/kinesis_e2e.yaml"
  pull_request:
    paths:
      - "packages/kinesis/**"
      - ".github/workflows/kinesis_e2e.yaml"
  workflow_dispatch:

defaults:
  run:
    shell: bash

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kinesis-data-streams-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Git Submodules
        run: git submodule update --init

      - name: Setup Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # 2.21.0
        with:
          cache: true
          channel: stable

      - name: Setup Dart
        uses: dart-lang/setup-dart@03a180dbe1de8ea7fb700663cbb7d24ca4bbe82c # main
        with:
          sdk: stable

      - name: Install native sqlite3
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Setup aft
        run: dart pub global activate -spath packages/aft

      - name: Bootstrap
        id: bootstrap
        timeout-minutes: 20
        run: aft bootstrap --fail-fast --include=aws_kinesis_datastreams --verbose

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@04b98b3f9e85f563fb061be8751a0352327246b0 # 3.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch Kinesis E2E secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@022e8919774ecb75e8e375656d7b1898936ab878 # 1.0.4
        with:
          secret-ids: |
            KINESIS_E2E,${{ secrets.KINESIS_E2E_SECRET_ARN }}
          parse-json-secrets: true

      - name: Run E2E tests
        working-directory: packages/kinesis/aws_kinesis_datastreams
        env:
          TEST_ACCESS_KEY_ID: ${{ env.KINESIS_E2E_ACCESS_KEY_ID }}
          TEST_SECRET_ACCESS_KEY: ${{ env.KINESIS_E2E_SECRET_ACCESS_KEY }}
          TEST_REGION: ${{ secrets.AWS_REGION }}
          TEST_STREAM_NAME: ${{ env.KINESIS_E2E_STREAM_NAME }}
        run: dart test test/e2e/ --tags=e2e

      - name: Log success/failure
        if: always()
        uses: ./.github/composite_actions/log_cw_metric_wrapper
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

          job-status: ${{ job.status }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          test-type: e2e
          working-directory: packages/kinesis/aws_kinesis_datastreams

          framework: dart
          flutter-dart-channel: stable
          dart-compiler: vm

  firehose-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Git Submodules
        run: git submodule update --init

      - name: Setup Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # 2.21.0
        with:
          cache: true
          channel: stable

      - name: Setup Dart
        uses: dart-lang/setup-dart@03a180dbe1de8ea7fb700663cbb7d24ca4bbe82c # main
        with:
          sdk: stable

      - name: Install native sqlite3
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Setup aft
        run: dart pub global activate -spath packages/aft

      - name: Bootstrap
        id: bootstrap
        timeout-minutes: 20
        run: aft bootstrap --fail-fast --include=aws_amazon_firehose --verbose

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@04b98b3f9e85f563fb061be8751a0352327246b0 # 3.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch Kinesis E2E secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@022e8919774ecb75e8e375656d7b1898936ab878 # 1.0.4
        with:
          secret-ids: |
            KINESIS_E2E,${{ secrets.KINESIS_E2E_SECRET_ARN }}
          parse-json-secrets: true

      - name: Run E2E tests
        working-directory: packages/kinesis/aws_amazon_firehose
        env:
          TEST_ACCESS_KEY_ID: ${{ env.KINESIS_E2E_ACCESS_KEY_ID }}
          TEST_SECRET_ACCESS_KEY: ${{ env.KINESIS_E2E_SECRET_ACCESS_KEY }}
          TEST_REGION: ${{ secrets.AWS_REGION }}
          TEST_DELIVERY_STREAM_NAME: ${{ env.KINESIS_E2E_DELIVERY_STREAM_NAME }}
        run: dart test test/e2e/ --tags=e2e

      - name: Log success/failure
        if: always()
        uses: ./.github/composite_actions/log_cw_metric_wrapper
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

          job-status: ${{ job.status }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          test-type: e2e
          working-directory: packages/kinesis/aws_amazon_firehose

          framework: dart
          flutter-dart-channel: stable
          dart-compiler: vm
