name: Verify Pub Constraints
on:
  schedule:
    - cron: "0 13 * * *" # Every day at 06:00 PST

jobs:
  test:
    name: Verify Pub Constraints
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          submodules: true

      - name: Setup Flutter
        uses: subosito/flutter-action@0ca7a949e71ae44c8e688a51c5e7e93b2c87e295 # 2.22.0
        with:
          cache: true
          channel: stable

      - name: Setup aft
        run: dart pub global activate -spath packages/aft

      - name: Verify Pub Constraints
        run: aft constraints pub-verify
